name: PR and Push Notification

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:  # ✅ This triggers the action on every push to any branch

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR/Push Notification Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🔔 Code Change Alert: ${{ github.event.head_commit.message || github.event.pull_request.title }}"
          body: |
            A new **code change** has been made in the repository.

            📌 **Repository:** ${{ github.repository }}
            👤 **Author:** ${{ github.actor }}

            🔹 **Commit Message:** ${{ github.event.head_commit.message || github.event.pull_request.title }}
            🔹 **Branch:** ${{ github.ref }}
            🔹 **Compare Changes:** ${{ github.event.compare || github.event.pull_request.html_url }}

            Click the link above to review the changes.

          to: "shrestha.saxena@flipkart.com"
          from: "GitHub Bot <shrestha.saxena@flipkart.com>"
