name: PR Notification

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Notification Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New PR Created: ${{ github.event.pull_request.title }}"
          body: "A new pull request has been created in the repository.\n\nDetails:\n- **PR Title:** ${{ github.event.pull_request.title }}\n- **PR Link:** ${{ github.event.pull_request.html_url }}\n- **Branch:** ${{ github.event.pull_request.head.ref }}\n\nView the PR for more details."
          to: "your-email@example.com"
          from: "GitHub Bot <your-email@example.com>"
